const rentHomes_data = [
    {
        '_id': '1',
        'title': 'Arman Tower',
        'address': 'Rajshahi',
        'description': 'Large apartment, Good window view, neighbours are humble',
        'image': '/images/RentHomes/Rent_a_home.webp',
        'rentperDuration': 500,
        'duration' : 'month',
        'status': 'Available',
        'contact_no': '01710123456',
        'contact_email': 'ff@gmail.com',
        'no_bedrooms': '4',
        'no_bathrooms': '4',
        'no_kitchens': '4',
        'no_parkings': '4',
        'square_footage': '1500',
    },
    {
        '_id': '2',
        'title': 'Arman Tower',
        'address': 'Rajshahi',
        'description': 'Large apartment, Good window view, neighbours are humble',
        'image': '/images/RentHomes/Rent_a_home.webp',
        'rentperDuration': 500,
        'duration' : 'month',
        'status': 'Available',
        'contact_no': '01710123456',
        'contact_email': 'ff@gmail.com',
        'no_bedrooms': '4',
        'no_bathrooms': '4',
        'no_kitchens': '4',
        'no_parkings': '4',
        'square_footage': '1500',
    },
    {
        '_id': '3',
        'title': 'Arman Tower',
        'address': 'Rajshahi',
        'description': 'Large apartment, Good window view, neighbours are humble',
        'image': '/images/RentHomes/Rent_a_home.webp',
        'rentPerDuration': 500,
        'duration' : 'month',
        'status': 'Available',
        'contact_no': '01710123456',
        'contact_email': 'ff@gmail.com',
        'no_bedrooms': '4',
        'no_bathrooms': '4',
        'no_kitchens': '4',
        'no_parkings': '4',
        'square_footage': '1500',
    },
    
    {
        '_id': '4',
        'title': 'Arman Tower',
        'address': 'Rajshahi',
        'description': 'Large apartment, Good window view, neighbours are humble',
        'image': '/images/RentHomes/Rent_a_home.webp',
        'rentPerDuration': 500,
        'duration' : 'month',
        'status': 'Not Available',
        'contact_no': '01710123456',
        'contact_email': 'ff@gmail.com',
        'no_bedrooms': '4',
        'no_bathrooms': '4',
        'no_kitchens': '4',
        'no_parkings': '4',
        'square_footage': '1500',
    },
    
]

export default rentHomes_data;