# Generated by Django 3.2.13 on 2022-06-04 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20220603_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renthome',
            name='no_badrooms',
        ),
        migrations.AddField(
            model_name='renthome',
            name='no_bedrooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='SellHome',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('no_bedrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('no_bathrooms', models.IntegerField(blank=True, default=0, null=True)),
                ('no_kitchens', models.IntegerField(blank=True, default=0, null=True)),
                ('no_parkings', models.IntegerField(blank=True, default=0, null=True)),
                ('square_footage', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('contact_no', models.IntegerField(blank=True, default=0, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=600, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('confirmDate', models.DateTimeField(auto_now_add=True)),
                ('SellHome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.renthome')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
