# Generated by Django 3.2.13 on 2022-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220906_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthome',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellhome',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
