# Generated by Django 3.2.13 on 2022-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
