# Generated by Django 3.2.13 on 2022-09-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_notification_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='owner',
            new_name='user',
        ),
    ]
