# Generated by Django 3.2.13 on 2022-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
